In [2]:
import pandas as pd
from json import load, dump

In [3]:
with open('../data/video_details_new.json') as f:
    video_details = load(f)['video_details']

In [39]:
df = pd.DataFrame.from_dict(video_details)
print(df.shape)
df.head()

(104, 12)

,videoId,publishedAt,channelId,channelTitle,title,description,tags,categoryId,duration,viewCount,likeCount,commentCount
0,1z5-O7-5AXk,2022-11-07T16:53:03Z,UCCWi3hpnq_Pe03nGxuS7isg,CampusX,Session 1 - Python Fundamentals | CampusX Data...,📃Chapters\n✒ Topic 0 - Introduction\n00:00:00 ...,"Education, Engineering, Campus, Placement, Ski...",27,PT2H10M23S,46005,1130,75
1,JCkIrdrZEE8,2022-11-08T16:48:45Z,UCCWi3hpnq_Pe03nGxuS7isg,CampusX,Session 2 - Operators + If-Else + Loops | Cam...,Session 2 - Operators + If-Else + Loops | Cam...,"Education, Engineering, Campus, Placement, Ski...",27,PT2H11M35S,19090,528,36
2,6HAu0Y9BjA4,2022-11-09T16:57:39Z,UCCWi3hpnq_Pe03nGxuS7isg,CampusX,Session 3 - Python Strings | CampusX Data Sci...,Session 3 - Python Strings | CampusX Data Sci...,"Education, Engineering, Campus, Placement, Ski...",27,PT2H22M54S,16491,400,20
3,7ltjqU5iytY,2022-11-10T07:34:36Z,UCCWi3hpnq_Pe03nGxuS7isg,CampusX,Programming Problems on Strings | Session 3 Su...,Programming Problems on Strings | Session 3 Su...,"Education, Engineering, Campus, Placement, Ski...",27,PT29M12S,6943,199,27
4,vg7BRC7wd0c,2022-11-10T17:01:20Z,UCCWi3hpnq_Pe03nGxuS7isg,CampusX,How to Build a Portfolio Website for Data Science,Portfolio Website Examples-\nhttps://www.kunal...,"Education, Engineering, Campus, Placement, Ski...",27,PT48M14S,12066,540,46

### The these cols because they have only one unique value.

In [40]:
df.drop(columns=['description', 'title', 'channelTitle', 'channelId', 'categoryId', 'tags'],
        inplace=True)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   videoId       104 non-null    object
 1   publishedAt   103 non-null    object
 2   duration      103 non-null    object
 3   viewCount     48 non-null     object
 4   likeCount     103 non-null    object
 5   commentCount  103 non-null    object
dtypes: object(6)
memory usage: 5.0+ KB

In [13]:
# Datetime cols
df['publishedAt'] = df['publishedAt'].astype('datetime64')

In [52]:
# Get length of video in minutes from duration column
hour = df['duration'].str.extract(r'(\d)H').fillna(0).astype(int)
minute = df['duration'].str.extract(r'(\d{2})M').fillna(0).astype(int)

df['duration'] = hour.mul(60).add(minute)

In [53]:
df.head()

,videoId,publishedAt,duration,viewCount,likeCount,commentCount
0,1z5-O7-5AXk,2022-11-07T16:53:03Z,130,46005,1130,75
1,JCkIrdrZEE8,2022-11-08T16:48:45Z,131,19090,528,36
2,6HAu0Y9BjA4,2022-11-09T16:57:39Z,142,16491,400,20
3,7ltjqU5iytY,2022-11-10T07:34:36Z,29,6943,199,27
4,vg7BRC7wd0c,2022-11-10T17:01:20Z,48,12066,540,46

1. Do some graphs stuffs.
2. Focus more on the datetime column.